### ISSUE TITLE
Guides Issue: Backing Up, Restoring, and Migrating Resources with Velero

### ISSUE THREAD

**Issue by eleanor-millman** [vmware-tanzu/tanzu-dev-portal#1006]
**Describe the bug**
Broken link on the Velero page.

**To Reproduce**
1. Go to 'https://tanzu.vmware.com/developer/guides/kubernetes/what-is-velero/'
2. Click on 'Backup and Restore' (near the bottom)
3. I am taken to this link but see a 404: https://kube.academy/lessons/backup-restore . Even when I log into KubeAcademy, I still see a broken link.

**Expected behavior**
I either expect not to get a 404, or the link should be removed.

**Desktop (please complete the following information):**
Chrome

**Comment by BrianMMcClain** [comment]
Thanks for the heads up @eleanor-millman! I've updated the link on the page to what I believe is the current one. Let me know if this still isn't correct and it should be changed to something else, and I'll be happy to update it!
