### ISSUE TITLE
Tanzu.TV Issue: Newly Native with Josh Long

### ISSUE THREAD

**Issue by Almar** [vmware-tanzu/tanzu-dev-portal#1026]
**Describe the bug**
Clicking on the video still navigates to VMwareTanzu videos on Twitch - the 'home page', *not* the specific video. In the end I did find the video but the link could be more helpful ;-)

**To Reproduce**
1. Go to: https://tanzu.vmware.com/developer/tv/
2. Click on: Subject of interest. Then click on video still
3. Browser will navigate to VMwareTanzu 'home page' of twitch.tv, *not* the selected video

**Expected behavior**
I expect to be navigated to the clicked video

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 91

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by bryanfriedman** [comment]
This only happens before we upload the YouTube video.
