### ISSUE TITLE
decompose development rhythm epic into content stories

### ISSUE THREAD

**Issue by andreas-eiken** [vmware-tanzu/tanzu-dev-portal#1082]

**Comment by billkable** [comment]
@andreas-eiken Please review the following issues and give feedback if necessary:

- [Course Epic](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1039)
- [Series (Course) outline and landing page](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1090)
- [Foundations article](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1091)
- [Development Flow article](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1096)
- [Building Blocks, Part 1 article](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1092)
- [Building Blocks, Part 2 article](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1093)
- [Development Rhythm Video](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1097)
- [Development Rhythm Workshop](https://github.com/vmware-tanzu/tanzu-dev-portal/issues/1098)

They are all labeled with content and app-dev.

The articles, video and workshop issues all reference the epic issue.
