### ISSUE TITLE
Reorganize CNR Library Conent

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu/tanzu-dev-portal#1130]
There are a number of articles under the Kubernetes topic that were migrated over from the [internal CNR site](https://cnr.eng.vmware.com/library/) (VPN required).  I would like to re-implement the categorization that you see in that legacy site.  Those articles have lost some usefulness since getting mixed in with a larger set of content and the categories removed.

Proposal:
- Add a new item to the "Learn" menu: "Library"
- Create a dedicated section for this content (similar to the Outcomes section) that follows the same categories and organization as the legacy site

**Comment by bryanfriedman** [comment]
Stale.
