### ISSUE TITLE
Publish a public version of "FAQ: MAPBU App Services Engineer"

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#1196]
Source: https://confluence.eng.vmware.com/pages/viewpage.action?spaceKey=VPL&title=FAQ%3A+MAPBU+App+Services+Engineer

Considerations:
- Remove consulting-specific language: client => team member; engagement => project, etc.
- Reference TDD article instead of duplicating it: https://tanzu.vmware.com/developer/learningpaths/application-development/test-driven-development/
- Reference pair programming article instead of duplicating it: https://tanzu.vmware.com/developer/learningpaths/application-development/pair-programming/

**Comment by anthonyvetter** [comment]
Link: https://tanzu.vmware.com/developer/guides/tanzu-labs-engineer-faq/
