### ISSUE TITLE
Address Bootstrap deprecation warning

### ISSUE THREAD

**Issue by BrianMMcClain** [vmware-tanzu/tanzu-dev-portal#1199]
With the style change in #1160 we updated to a newer version of Bootstrap, which while long overdue, now produces this warning:

```
WARNING: The `bg-gradient-variant` mixin has been deprecated as of v4.5.0. It will be removed entirely in v5.
         on line 8:5 of themes/docsy/assets/vendor/bootstrap/scss/mixins/_deprecate.scss, in mixin `deprecate`
         from line 21:12 of themes/docsy/assets/vendor/bootstrap/scss/mixins/_background-variant.scss, in mixin `bg-gradient-variant`
         from line 37:18 of assets/scss/_boxes.scss, in mixin `box-variant`
         from line 121:14 of assets/scss/_boxes.scss
         from line 14:9 of stdin
```

This only seems to appear in the one file listed in the error, `assets/scss/_boxes.scss` on [lines 36-38](https://github.com/vmware-tanzu/tanzu-dev-portal/blob/main/assets/scss/_boxes.scss#L36-L38)

```
@if $enable-gradients {
        @include bg-gradient-variant("#{$parent}--1#{$color-name}#{$parent}--gradient", $color-value);
    }
```

In the [Bootstrap 5.0 Migration Guide](https://getbootstrap.com/docs/5.0/migration/), they address this with the following:

> Removed the bg-gradient-variant() mixin. Use the .bg-gradient class to add gradients to elements instead of the generated .bg-gradient-* classes.

**Comment by bryanfriedman** [comment]
This doesn't appear to be an issue anymore.
