### ISSUE TITLE
Learning Path Title should be shifted to centered over content, vs whole page

### ISSUE THREAD

**Issue by jonasmit** [vmware-tanzu/tanzu-dev-portal#1328]
Looking at learning paths, it seems to me that the title and metadata for the learning path (duration, etc.) should be aligned with the contents of the article rather than with centered for the whole.  page. It looks off balance to me.

Filing as a bug, but perhaps this was intentional.

![Screen Shot 2021-10-05 at 12 47 40 PM](https://user-images.githubusercontent.com/551536/136067248-9a3d52a9-c856-42e4-8845-eef985cf43bc.png)

Perhaps we could also add a styled table to format the metadata as well

e.g. something similar to this 
![Screen Shot 2021-10-05 at 12 50 37 PM](https://user-images.githubusercontent.com/551536/136067490-d505c047-1851-49ad-818c-b7ee66306c70.png)

**Comment by bryanfriedman** [comment]
The navigation is part of the Learning Path so I think it's right how it is.
