### ISSUE TITLE
Practice: Feature Funnel

### ISSUE THREAD

**Issue by mawei14** [vmware-tanzu/tanzu-dev-portal#1463]
## Summary
This is an activity that shows sequential steps to filter feature requests so that product teams are only working on validated items aligning with your product strategy and will build towards the product vision. It provides a good framework to push back on feature requests with thoughtful and comprehensive answers based on mini version of existing Tanzu practices.

## Progress and Publication Status
- [X] Partially written and/or draft in progress

## Maturity of this Practice
- [x] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

## Resources 
https://miro.com/app/board/uXjVOdDEoY0=/?invite_link_id=15402309008

---

## Getting Started
- Please review the [Contribution Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki)
- Ready to start writing? Please use this [Tanzu Practice Template](https://docs.google.com/document/d/1ys0JUDF1VPXwcD65dSe3VZBr5MCl9FFSJWPYXeQLMC8)

## Where should I Publish This Tanzu Practice?
It depends!

The mission for this content is to help our people and others self-service their way to successful software product outcomes. 

First ask “is this a Core Method?” A method can be defined as "any process or template that can be utilized to go from point A to point B, in order to help in decision-making and move the project towards success."

A Core Method should have the following properties:
- Generally applicable to software product teams
- Teams consistently see value from the method
- Its success has been repeated
- You are likely to use this method in the future, either on the same project or other projects
- While everything evolves, this method is not under constant and dramatic change

If the method meets these criteria then it is a strong candidate for the Practices section of the public, open source Tanzu Developer Center.

If this method does not meet those criteria then it might be more appropriate to publish it internally to our company Confluence. For example, if you chose a Publication Status of "Not yet written" and Maturity of "Immature" above then consider documenting this method internally, applying it in more situations and have others do the same. Iterate on the method or practice until it is more stable.

**Comment by mawei14** [comment]
I am currently working on a Google doc for this. Should be done very soon

**Comment by joemoore** [comment]
Thank you @mawei14! I look forward to check it out. 

I did noticed that you marked this Practices as "Incubating". Do you have any thoughts about that based on the guidance in "Where should I Publish This Tanzu Practice?" above? Specifically: 

> ... if you chose a Publication Status of "Not yet written" and Maturity of "Immature" above then consider documenting this method internally _[edit: such as in Confluence]_, applying it in more situations and have others do the same. Iterate on the method or practice until it is more stable.

Thoughts?

**Comment by mawei14** [comment]
Hey @joemoore, that sounds good! Sorry, I hadn't read the whole prompt and had just been putting in placeholder text to get it started. I'll close out the issue and post what I've written on Confluence
