### ISSUE TITLE
Leadership Roles & Accountabilities

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#1494]
## Summary
For a new practice: a short summary, a few sentences at most.

For changes to an already-published practice: provide the link and describe your proposed change.

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [x] Partially written and/or draft in progress
- [ ] Not yet written

## Maturity of this Practice
- [ ] Very Mature: well established and widely used by our organization and others
- [x] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

## Resources 
Draft: [List anything here that might be helpful for writing this article.
](https://docs.google.com/document/d/1cgadLoHT_qNuJS0zPiZcRcy2MJSWrKkMR1ta_zQw2rQ/edit)

## Contribution Guide
Please refer to the [Tanzu Practices Contrition Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Tanzu-Labs-Practices-Contribution-Guide) for detailed instructions.

**Comment by joemoore** [comment]
Being worked on by @bhyde-vmware

**Comment by bhyde-vmware** [comment]
Looks like this might have gotten all the feedback it's going to get at this time I've year. I'm comfortable shipping it if you are @joemoore

**Comment by anthonyvetter** [comment]
Link: https://tanzu.vmware.com/developer/practices/leadership-roles-and-accountabilities/
