### ISSUE TITLE
Architectural Decision Records: What were the engineers thinking?

### ISSUE THREAD

**Issue by cserrant** [vmware-tanzu/tanzu-dev-portal#1499]
## Summary of content
1100 word article about Architecture Decision Records. ADRs serve as a snapshot into the developer's past, and grants thoughts and insights about important technical decisions.

## Summary of audiences
- Software Developers of all skill levels.
- Product developers and designers who want to coordinate more with engineers.
- Project managers and stakeholders who want to understand important decisions.

## Level of content
- 101: "Awareness / Exploration"

## Contributor Checklist
1. [x] I have added a card to the [GitHub Content Backlog](https://github.com/vmware-tanzu/tanzu-dev-portal/projects/7) and/or moved it to the proper column. See [Content Prewriting and Ideation](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Prewriting-Ideation-(GitHub-and-Google-Docs-Method))
2. [x] **If contributing via Google Docs**: I have added a link to my document to this issue, and set the document's Share settings to "Anyone on the internet with this link can comment". [Draft is here](https://docs.google.com/document/d/1pFHe3xlcfiNzjBIOmMM79zqx2uvEWXk47sWfjXSDhjI/edit?usp=sharing)
3. [x] My content is drafted in accordance with existing [style guides](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Reference,-Style-Guide) and best practices. See [Drafting Content](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Drafting-Content-(GitHub-Method)) 
4. [x] The front matter (metadata) is filled out completely (e.g. description, topics, tags, author, etc - as appropriate for the content type). See [Drafting Content](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Drafting-Content-(GitHub-Method))
5. [x] My content has been reviewed by my team for technical accuracy. See [Editing Content](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Editing-Content-(GitHub-and-Google-Docs-Method))
6. [x] My content has beed reviewed and edited by a copy editor. See [Editing Content](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Editing-Content-(GitHub-and-Google-Docs-Method))
7. [x] **If applicable**: My content has gone through a legal review (**VMware Employees Only**). See [Editing Content](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Editing-Content-(GitHub-and-Google-Docs-Method))
8. [x] **If applicable**: I have tested my content locally and everything passes. See [Testing Content](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Testing-Content-(GitHub-Method))
9. [ ] **Optional**: I have filled out the [Social Media request form](https://docs.google.com/forms/d/e/1FAIpQLSfyWYEL6XvDRfMRW1GBfYKV4Aq3Li2EzBz0HY8fE37Y2tSoRw/viewform) (optional) (**VMware Employees Only**). See [Next Steps](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Next-Steps)
10. [ ] **If applicable**: I have created an author page and opened a pull request to get it added. See [Next Steps](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Next-Steps)

## Reviewer Checklist

* [x] Review if the content is a good fit for the Tanzu Developer Center. See [Content Prewriting and Ideation](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Contribution,-Prewriting-Ideation-(GitHub-and-Google-Docs-Method))
* [x] There this GitHub issue has been added to the [content backlog project](https://github.com/vmware-tanzu/tanzu-dev-portal/projects/7) 
* [x] Ensure with the author that the content has been reviewed for technical accuracy.
* [x] Ensure with the author that the content has been through copy editing.
* [x] **If applicable**: Ensure with the author that the content has been through Legal review.
* [x] Review fit with the [Tanzu Developer Center Style Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Reference,-Style-Guide) and the [VMware Style Guide](https://www.vmware.com/content/dam/brand/photography-only/guidelines/writing-and-naming/editorial-style-guide/marketing-editorial-style-guide.pdf) (**VMware Employees Only**). 
* [x] Ensure the front matter is filled out correctly and completely.
* [x] **If applicable**: Review additions to `custom_dict.txt`.
* [x] Ensure with the author they have reviewed the staging site for correctness. The reviewer should review this too.
* [ ] **If applicable**: Review any new Team pages.
* [ ] **Optional**: Ensure the author has provided copy for Social Media distribution.\
* [ ] **If contributing via Google Docs**: Send the staging link to the author to review. The reviewer should review this too. Get the final 👍 from the author to push the content public.

**Comment by anthonyvetter** [comment]
[Link to Google Doc](https://docs.google.com/document/d/1pFHe3xlcfiNzjBIOmMM79zqx2uvEWXk47sWfjXSDhjI/edit#)

Nice work! 

Not my area of expertise but this seems pretty applicable to me. One question I had while reading, when you say "Put it in the repository", Would this just be a dir full of files? Or would these be part of a commit log? Or something else? Are there best practices for this? Like I said, not my area of expertise so if you think this point will be obvious to all/most readers, then maybe there is no need to be more explicit. But it seemed like an area to maybe add some more detail.

**Comment by anthonyvetter** [comment]
Any other feedback on this? Or should we get it in front of copy editing?

**Comment by cserrant** [comment]
Thank you taking a look. I think it's ready for copy editing.

**Comment by anthonyvetter** [comment]
Submitted for editing. Stand by. Suggestions will be made in the Google Doc for you to accept/decline.

**Comment by anthonyvetter** [comment]
Deploy preview ready: https://deploy-preview-1529--tanzu-dev-portal.netlify.app/developer/guides/architectural-design-records-what-were-the-engineers-thinking/

Let me know if you want to see any changes, or if looks ready to ship from your POV.

**Comment by cserrant** [comment]
Thank you for the preview. I reread the document and I made some edits to the Google Drive document. You can see them on the "version history" section (cmd option shift + H on Mac, or you can search for it in the help menu.) Most of the edits are in the introduction.

**Comment by anthonyvetter** [comment]
Live link: https://tanzu.vmware.com/developer/guides/architectural-design-records-what-were-the-engineers-thinking/
