### ISSUE TITLE
CSS drop-down menu visualisation problem

### ISSUE THREAD

**Issue by dlion** [vmware-tanzu/tanzu-dev-portal#1542]
**Describe the bug**
Hi,
I don't know if this problem has been already reported but there is a visualization problem on the drop-down menu probably due to a CSS error as you can see in the screenshot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://tanzu.vmware.com/developer/learningpaths/
2. Put the cursor on the "Learn" menu
3. You can see the CSS problem

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/2125236/150510719-79e171ff-fec4-488e-918f-54ca14136a74.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser Brave
 - Version 1.34.80

** Notes **

It also happens hovering on both `Tanzu.TV` and `Community` menus.

**Comment by danielramirez0** [comment]
@dlion Is this issue occurring during a preview of the site or when you view the actual site? I'm not able to reproduce this issue on Brave with the live site.  Site note, however, I have also seen this issue during a local preview with longer names on the community dropdown.

**Comment by dlion** [comment]
Hi @danielramirez0 , it's the live site.
I don't have specific extensions that could have impacted my experience
I just visited  https://tanzu.vmware.com/developer/learningpaths/ and moved the cursor over the menu.
![image](https://user-images.githubusercontent.com/2125236/150943046-c77d8dda-0bc4-40d4-9164-1da005d05055.png)

I tried to visit the website on Safari and it works fine so I guess it's just my brave instance for some reason 🤔

**Comment by danielramirez0** [comment]
Unable to replicate issue on any browser (tested with Chrome, Edge, Safari, and Brave).
