### ISSUE TITLE
Determine why local Hugo server messes with some Javascript

### ISSUE THREAD

**Issue by BrianMMcClain** [vmware-tanzu/tanzu-dev-portal#163]
First noticed when testing #161, it seems there's some caching going on of some objects when using the local Hugo testing webserver. There's a few flags that could be used that might fix it, just need to figure out the correct ones.

**Comment by bryanfriedman** [comment]
No solution here but I believe this is a similar problem: https://discourse.gohugo.io/t/hugo-pipes-scss-not-re-compiling-on-server-or-watch/14435

It seems to have to do with the Hugo Pipes that are building the JS assets...

**Comment by bryanfriedman** [comment]
Chances of solving this are low. Chances of it coming up again are also low.
