### ISSUE TITLE
Personal User Manual

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#1777]
## Summary
How to write a "user manual to me" for others to understand how to work with you.

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [ ] Partially written and/or draft in progress
- [x] Not yet written

## Maturity of this Practice
- [x] Very Mature: well established and widely used by our organization and others
- [ ] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

## Resources 
- [Atlassian: My User Manual](https://www.atlassian.com/team-playbook/plays/my-user-manual)
- [Communicating to yourself and others — Your Personal User Manual and other great tools](https://medium.com/10x-curiosity/communicating-to-yourself-and-others-your-personal-user-manual-and-other-great-tools-cb015400ee02)

## Contribution Guide
Please refer to the [Tanzu Practices Contrition Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Tanzu-Labs-Practices-Contribution-Guide) for detailed instructions.

**Comment by amandawhitevmware** [comment]
I have some beach time today I'm gonna try to work on this @joemoore

**Comment by amandawhitevmware** [comment]
Draft https://docs.google.com/document/d/1GNWTK1v9mna6SKo-DJAXSzL9WpxDbyGAAZG-TlVy-tU/edit

**Comment by joemoore** [comment]
Hi! I'll assign this to you and move it into the in-progress column

**Comment by joemoore** [comment]
Live at https://tanzu.vmware.com/developer/practices/personal-user-manual/
