### ISSUE TITLE
Tests can sometimes fail with an HTTP 500 response from DockerHub

### ISSUE THREAD

**Issue by BrianMMcClain** [vmware-tanzu/tanzu-dev-portal#1884]
Ref: https://github.com/vmware-tanzu/tanzu-dev-portal/runs/6863069364?check_suite_focus=true

```
   Sending build context to Docker daemon  6.144kB
  
  Step 1/18 : FROM alpine:3.16.0
  Head "https://registry-1.docker.io/v2/library/alpine/manifests/3.16.0": received unexpected HTTP status: 500 Internal Server Error
Error: Docker build failed with exit code 1
```

Perhaps need to investigate if there's a way to cache the built test container image if no changes to the Dockerfile/test has been made?

**Comment by bryanfriedman** [comment]
updated act version, have not seen this issue.
