### ISSUE TITLE
Mobile social banner improvements

### ISSUE THREAD

**Issue by jldec** [vmware-tanzu/tanzu-dev-portal#213]
The color of the social banner on mobile is quite a lot brighter and (imo) distracts from the rest of the page.
Maybe you could make it disappear to free up more space when the page has been scrolled down? 
(I have a new iphone SE running Safari, so the screen is smallish)

![IMG_5BA783B4F911-1](https://user-images.githubusercontent.com/849592/89901042-70cd1d00-dbdc-11ea-835f-ead06a00e983.jpeg)

**Comment by BrianMMcClain** [comment]
@bryanfriedman this brings up a good point, do we still show the social share links anymore? I just realized I haven't seen them in a bit, but I'm wondering if it has something to do with my local config or it's site-wide. Curious if it is site-wide, did this get lost when we added the cookie notice?

**Comment by BrianMMcClain** [comment]
Alright, looks like it was something local to me that was blocking the social banner on desktop, but I can't for the life of me get it to show on mobile at all, so updating this issue to include looking into why that's the case as well

**Comment by jldec** [comment]
I don't see the bar at the bottom anymore - but noticed that the menu button is being overlaid with the word "Center"

![IMG_6C3580BDE61C-1](https://user-images.githubusercontent.com/849592/109795969-7e490380-7c0f-11eb-84af-dc55c4b6154f.jpeg) ![IMG_92F3EAA32D02-1](https://user-images.githubusercontent.com/849592/109796267-d5e76f00-7c0f-11eb-8331-85c9c4b4d28c.jpeg)
