### ISSUE TITLE
Practice: Impact Analysis

### ISSUE THREAD

**Issue by lucaishovmware** [vmware-tanzu/tanzu-dev-portal#2222]
## Summary
For a new practice: a short summary, a few sentences at most.

A system way to assess the impact a particular workflow is costing an enterprise (cost, time, resources, etc.). This will help organisations to quantify and validate the need to improve on a business driver/drivers.

Example: Company A is thinking of introducing an online application which will automate a manual process. By carrying out an impact analysis, the company has assessed that $Y / annum is spent on this manual process, and the introduction of an online app will automate said process, resulting in Z savings in time and dollars.

For changes to an already-published practice: provide the link and describe your proposed change.

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [ ] Partially written and/or draft in progress
- [x] Not yet written

## Maturity of this Practice
- [ ] Very Mature: well established and widely used by our organization and others
- [ ] Mature: have successfully used many times with many teams / projects
- [x] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

## Resources 
List anything here that might be helpful for writing this article.

- Links to articles and blog posts
- Links to presentations, videos, books, etc.

https://docs.google.com/presentation/d/1W7P0JvKxAi66i6bXMfdEl8AQEHEYgXWX6-Fzc2Z-6n8/edit?usp=sharing

## Contribution Guide
Please refer to the [Tanzu Practices Contrition Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Tanzu-Labs-Practices-Contribution-Guide) for detailed instructions.

**Comment by joemoore** [comment]
Assigned to @lucaishovmware

**Comment by joemoore** [comment]
Please take a look at the [Practice Contribution Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Tanzu-Labs-Practices-Contribution-Guide) for guidance around drafting and seeking feedback about this workshop.
