### ISSUE TITLE
Videos from Tanzu TV do not show up under people's pages

### ISSUE THREAD

**Issue by tiffanyfay** [vmware-tanzu/tanzu-dev-portal#269]
Currently if you click on a specific person, their videos from Tanzu TV shows do not show up in the videos section.

It will need to be determined how to choose when to put someone since for instance, Tanzu TV the "guest" is the primary speaker and for Code the "host" is the primary speaker.

**Comment by bryanfriedman** [comment]
Need to add some logic to: https://github.com/vmware-tanzu/tanzu-dev-portal/blob/main/themes/docsy/layouts/team/team.html
