### ISSUE TITLE
Improve support of external people

### ISSUE THREAD

**Issue by paulczar** [vmware-tanzu/tanzu-dev-portal#292]
Currently people are managed in the /team folder.  We need to be able to add external people that shouldn't show up on the `teams` page.  

In this PR https://github.com/vmware-tanzu/tanzu-dev-portal/pull/289 we added an `external` parameter, we should look at keying off their existing `roles` rather than adding extra fields.  We may also want to do `people/team` and `/people/external` for easier organization as they grow.

**Comment by tiffanyfay** [comment]
@paulczar So if it got moved into people/team and people/external, are you suggesting a page that links to both, or merely how it is internally for each group? Because right now advocates are under its own folder.

**Comment by bryanfriedman** [comment]
Maybe explore adding a team "type" or something along those lines. This would potentially solve the problem of external folks but also support the ability to add internal subteams a la Tanzu Labs or Advocates to handle special cases.

**Comment by bryanfriedman** [comment]
We did this already. Just add `external: true`.
