### ISSUE TITLE
Better responsiveness on new Guides page

### ISSUE THREAD

**Issue by bryanfriedman** [vmware-tanzu/tanzu-dev-portal#502]
Add widescreen view so the reading column widens if the window is very wide. 

Also fix what happens between 768 and 1199. Either trigger the behavior that occurs at 767 at 1199 instead, or remove the `no-wrap` class on the row and add something like `max-width:75%` to `main` at widths larger than 767.

**Comment by jesse-martinez** [comment]
I fixed the second part of your card in my upcoming PR but the first part I'm a bit torn on. I tried doing something like this but it feels off? Looks like the right side is empty. But if I extend the whole reading container in the middle then it just feels like a lot of text horizontally across the screen. Lemme know what you think.

![Screen Shot 2021-03-31 at 8 43 47 PM](https://user-images.githubusercontent.com/43387716/113240780-36df8280-9262-11eb-94e2-4aaa0f70a118.png)
