### ISSUE TITLE
Some wide code blocks aren't being made horizontally-scrollable

### ISSUE THREAD

**Issue by BrianMMcClain** [vmware-tanzu/tanzu-dev-portal#570]
ie. /guides/kubernetes/workload-tenancy-platform-checklist/

**Comment by zmb3** [comment]
Surely an issue with the `checklist-item` shortcode, which we may not even need. I'm not convinced we need the interactivity of being able to check a box.

**Comment by zmb3** [comment]
Looks better now:

![image](https://user-images.githubusercontent.com/7527103/109178248-e26a5400-7745-11eb-969d-cfbb3457270c.png)
