### ISSUE TITLE
Upgrade hugo version?

### ISSUE THREAD

**Issue by bryanfriedman** [vmware-tanzu/tanzu-dev-portal#585]
https://github.com/vmware-tanzu/tanzu-dev-portal/blob/ef2611b47068f58435f3ef64fedeafca7a03e636/netlify.toml#L7

We probably don't need to pin to this version anymore... Do we have to specify a version at all or will Netlify just grab the latest? Do we want to grab the latest or should we pick a (newer) stable version to make sure it's a safe/consistent build?

**Comment by BrianMMcClain** [comment]
My vote would be to keep it pinned to a specific version, at least a specific major/minor version, but I think it would be good to looking into updating it. My only just having it grab whatever's latest on pull is that it becomes a bit harder to verify potential breaking changes between versions.

**Comment by BrianMMcClain** [comment]
Recently upgraded to 0.82 in #705
