### ISSUE TITLE
Fix height of guides grid/list

### ISSUE THREAD

**Issue by zmb3** [vmware-tanzu/tanzu-dev-portal#628]
When the title of a guide is long and causes the bounding box to grow vertically we get a grid row that contains boxes with varying heights.

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/7527103/110826310-300cb380-8252-11eb-94ba-0ea31e5154e8.png">

All boxes in the row should be the same height.

**Comment by zmb3** [comment]
This issue only occurs with guides (workshops, for example, behaves correctly).

It looks like we're changing `.linked-box`'s CSS from `height: 100%` to `height: auto` for some reason on the guides.

https://github.com/vmware-tanzu/tanzu-dev-portal/blob/32db931b884403d67b1cc759a75ed5bed7883f48/themes/docsy/assets/scss/main.scss#L59-L62

**Comment by jesse-martinez** [comment]
This has been fixed, in my previous CSS adjustments PR.

**Comment by BrianMMcClain** [comment]
Fixed via #679

**Comment by zmb3** [comment]
Seeing the opposite behavior on Safari now - the grid items are the same height, but way too tall!

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/7527103/114748775-78b30300-9d0f-11eb-945a-00673ebd7539.png">

**Comment by BrianMMcClain** [comment]
Can confirm I'm seeing this as well, adding prio label to this
