### ISSUE TITLE
On This Page shows a scrollbar in MS Edge

### ISSUE THREAD

**Issue by bryanfriedman** [vmware-tanzu/tanzu-dev-portal#727]
![image](https://user-images.githubusercontent.com/7662510/115593805-d43e3d00-a289-11eb-88a4-a7d684fff9b4.png)

**Comment by BrianMMcClain** [comment]
Seeing this in Chrome as well, including a horizontal scroll bar. I assume this was added when we addressed the situation where there were a large number of headers on a page. I'm curious if there's a way to only show the scroll bar when there's too many to include on the page?

<img width="661" alt="Screen Shot 2021-04-27 at 1 03 40 PM" src="https://user-images.githubusercontent.com/1136557/116282628-00a9fb80-a759-11eb-86c7-43e618ac0bd3.png">


Ref: https://tanzu.vmware.com/developer/guides/containers/what-is-bitnami/
