### ISSUE TITLE
Add link to each page for feedback

### ISSUE THREAD

**Issue by mikegehard** [vmware-tanzu/tanzu-dev-portal#742]
"Have feedback, click here"

This will link the user to a GH issue template in this repo

**Comment by mikegehard** [comment]
@bryanfriedman @BrianMMcClain 

Are you all OK with me adding a link to every page (put it in the template), on a subset of the pages or just the workshop pages I care about?

**Comment by BrianMMcClain** [comment]
Sorry didn't see the comment here. I know we already chatted about this on Slack but just to record here for transparency: The end goal would be to have this enabled on all content (workshops, guides, videos, etc), but if we want to start with just workshops as a first step and see how that goes, I think that makes a lot of sense.

**Comment by BrianMMcClain** [comment]
Adding mockups from Rachel here for reference. We have a couple options on how we want to do it: we could have it in the right-hand nav on the guides as shown below: 

![image (1)](https://user-images.githubusercontent.com/1136557/116424348-707abd80-a80f-11eb-9801-c242dd8b2ac7.png)

This won't work for workshops for example, in which case we can include the link on the bottom of the page perhaps:

![image](https://user-images.githubusercontent.com/1136557/116424412-7ec8d980-a80f-11eb-9bcd-2bfd8b8f5d3c.png)

**Comment by mikegehard** [comment]
Neither of those treatments is ideal.

1. The right hand nav only shows up on some pages. And on the pages it does show up on, it scrolls off the top of the page for long articles. The user then loses visibility to the link.
2. Workshop pages, where feedback is important, do not have a footer so putting it at the bottom of the page isn't ideal.

What about putting it somewhere towards the top of the page, maybe as a 5th link in the header with a special treatment to call attention to it? The header is on all pages and it fixed at the top of the page during a scroll so it stays visible.

**Comment by BrianMMcClain** [comment]
@jesse-martinez following up on our chat earlier and wanted to record some of the things we talked about here for reference. As mentioned, this link is only on individual pieces of content (guide, sample, video, blog). The idea is that we'll update Hugo to generate a link per page to include the page title as a query param, which will link the person who clicks it to open a new issue in this repo using an existing issue template. The link will be "https://github.com/vmware-tanzu/tanzu-dev-portal/issues/new?assignees=&labels=bug&template=bug_report.md&title=" plus a descriptive value for `title` that includes the url-encoded page name/link.

The one wrinkle in this is to figure out how this works with live workshops. We're looking to allow those running through the workshops to report an issue if they run into one in the middle of their session. We're not exactly sure how to go about adding this. Bryan suggested a small overlay on the bottom-right corner, which I think sounds good. If that's not possible, we could look at a very small footer with the link.
