### ISSUE TITLE
Investigate failing Lighthouse checks / extend Netlify preview deploy timeout?

### ISSUE THREAD

**Issue by BrianMMcClain** [vmware-tanzu/tanzu-dev-portal#755]
Intermittently we've seen the Lighthouse action fail on PRs at the `wait_for_deploy_preview` step with the following:

```
1m 5s
Run jakepartusch/wait-for-netlify-action@v1
Waiting for a 200 from: https://deploy-preview-752--tanzu-dev-portal.netlify.app
Url unavailable, retrying...
Url unavailable, retrying...
[...]
Url unavailable, retrying...
Error: Timeout reached: Unable to connect to https://deploy-preview-752--tanzu-dev-portal.netlify.app
```

Every time I've seen this, the deploy does seem to be working fine by the time I check it, so perhaps we just need to up the timeout on this job?

**Comment by zmb3** [comment]
Alternatively, instead of waiting for the deploy preview and running checks against that, we could start a dev server in CI and run the lighthouse checks against localhost.

When I set it up I figured the deploy preview was closest to a prod-like environment, but we might get the same value out of a different setup.

**Comment by BrianMMcClain** [comment]
I was initially worried how that might affect the performance tests, but so long as we're building/running the site as Netlify is (ie. making sure we're minifying the JS and CSS), looking at the actual things it tests I think this might actually be fine. Might be a good idea to compare the tests of a local build vs Netlify preview build before we make changes just to ensure we're getting similar results.

**Comment by BrianMMcClain** [comment]
This may be unnecessary if we end up merging #842
