### ISSUE TITLE
Provide educates metrics for workshops

### ISSUE THREAD

**Issue by mikegehard** [vmware-tanzu/tanzu-dev-portal#759]
Currently we only have access to Google Analytics/DataStudio and Amplitude. Those are great for seeing how many hits the landing page for each workshop gets.

They do not provide any metrics about what folks are doing within the workshop like:
* How far do they get?
* Are there steps they get stuck on?

Having the workshop data would allow us to iterate to make the workshops better without direct feedback (which we would also like via #742).

**Comment by BrianMMcClain** [comment]
We did just merge #746, which collects events around when workshops are started, finished, abandoned, and an event as they progress through the workshop (ie. If they move on to the next step, an event is emitted to say they're 7% through the workshop). Does this combined with #742 achieve what you're looking for here?

**Comment by mikegehard** [comment]
@BrianMMcClain Quite possibly.

Where might I find a report that includes those metrics so I can take a look and answer that question?

**Comment by mikegehard** [comment]
Ideally a dashboard broken down by workshop would be ideal.

Some ideas for metrics by workshop:
% completion
step that most people fall out of the workshop at.

**Comment by bryanfriedman** [comment]
We have this now.
