### ISSUE TITLE
Describe how to go from code to container

### ISSUE THREAD

**Issue by craigtracey** [vmware-tanzu/tanzu-dev-portal#769]
Describe the various ways that a developer may build container images for their code.

- What are the various ways that I can build a container?
  - Docker
  - Tanzu Build Service
  - Kaniko
- Provide an example of how these build tools may be used in a CI/CD pipeline
- How can the build process be similar/same developer workflow?
- Where does image scanning fit in?
  - A failed scan should break the build

**Comment by BrianMMcClain** [comment]
We do have some existing guides around these topics if they're at all helpful (ie. building Docker containers, some info around kpack and the pack CLI, Nothing directly related to kaniko (though we do have a guide on [building images with Tekton using Kaniko](https://tanzu.vmware.com/developer/guides/ci-cd/tekton-gs-p2/)). If any of this is helpful to pull in or use as a starting point, I'm happy to gather what we have and/or readapt some of it

**Comment by BrianMMcClain** [comment]
Just to roundup some of the existing content if we'd like to reference/rewrite:

## Docker
- [What are Containers?](https://tanzu.vmware.com/developer/guides/containers/what-are-containers/)
- [Getting Started with Docker Containers on Kubernetes](https://tanzu.vmware.com/developer/guides/kubernetes/from-docker-to-kubernetes/)
- [Python Like a Pro: Building Docker Containers](https://tanzu.vmware.com/developer/guides/python/cnb-gs-python/)
- [From Commit to Container](https://tanzu.vmware.com/developer/blog/from-commit-to-container/)
- [Container Basics Workshop](https://tanzu.vmware.com/developer/workshops/lab-container-basics/)

## Tanzu Build Service
- [What are Cloud Native Buildpacks?](https://tanzu.vmware.com/developer/guides/containers/cnb-what-is/)
- [Getting Started with the pack CLI](https://tanzu.vmware.com/developer/guides/containers/cnb-gs-pack/)
- [Getting Started with kpack](https://tanzu.vmware.com/developer/guides/containers/cnb-gs-kpack/)
- [Spring Live: Build Images with Confidence and Ease with Cloud Native Buildpacks](https://tanzu.vmware.com/developer/videos/spring-live-buildpacks/)
- [Video: Getting Started with kpack](https://tanzu.vmware.com/developer/videos/kpack-gs/)

## Kaniko

We don't have a ton on Kaniko directly, but some content does mention it

- [Getting Started with Tekton Part 2: Building a Container](https://tanzu.vmware.com/developer/guides/ci-cd/tekton-gs-p2/)
- [TGIK 055: Building container with Kaniko](https://tanzu.vmware.com/developer/tv/tgik/0055/)

## CI/CD
- [What is CI/CD?](https://tanzu.vmware.com/developer/guides/ci-cd/ci-cd-what-is/)
- [Getting Started with ArgoCD on Kubernetes](https://tanzu.vmware.com/developer/guides/ci-cd/argocd-gs/)
- [Create a Continuous Integration Pipeline with GitLab and Kubernetes](https://tanzu.vmware.com/developer/guides/ci-cd/gitlab-auto-devops/)
- [Getting Started with Tekton Part 1: Hello World](https://tanzu.vmware.com/developer/guides/ci-cd/tekton-gs-p1/)
- [Getting Started with Tekton Part 2: Building a Container](https://tanzu.vmware.com/developer/guides/ci-cd/tekton-gs-p2/)
- [Getting Started with Concourse CI](https://tanzu.vmware.com/developer/guides/ci-cd/concourse-gs/)

## Developer Workflow

- [Developing Locally for the Cloud](https://tanzu.vmware.com/developer/blog/developing-locally-for-the-cloud/)
- Kubernetes at Home: Local k8s Options](https://tanzu.vmware.com/developer/blog/kubernetes-at-home-local-k8s-options/)
- [Continuously Develop and Monitor an Express Application on Kubernetes with Bitnami, Skaffold and Octant](https://tanzu.vmware.com/developer/guides/ci-cd/express-app-bitnami-skaffold-octant/)

## Image Scanning

- [Managing and Securing Container Images in a Registry](https://tanzu.vmware.com/developer/guides/containers/managing-container-images-registry/)
- [Best Practices for Securing and Hardening Container Images](https://tanzu.vmware.com/developer/guides/containers/security-best-practices/)
