### ISSUE TITLE
Pluses and Deltas - Partially Written / Draft

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#799]
Summary: an exercise for an engineering pair or other disciplines to do at end-of-day to reflect on the day and working with each other.

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [x] Partially written and/or draft in progress
- [ ] Not yet written

## Maturity of this Practice
- [ ] Very Mature: well established and widely used by our organization and others
- [x] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

Draft content: See internal VMware Confluence page "Practices and Workshops"

Contact with context: Erica Dohring

Draft content: See internal VMware Confluence page "Practices and Workshops"

**Comment by joemoore** [comment]
Update: The draft is done because the original author left the company, resulting in automatic deletion of the draft. 

---

## Getting Started
- Please review the [Contribution Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki)
- Ready to start writing? Please use this [Tanzu Practice Template](https://docs.google.com/document/d/1ys0JUDF1VPXwcD65dSe3VZBr5MCl9FFSJWPYXeQLMC8)

**Comment by pivot-carlos-poon** [comment]
This is something I have interest in helping out with. Gonna start with creating the Tanzu Practice Template.

**Comment by joemoore** [comment]
Great! I'll assign it to you and move it to "in progress"

**Comment by anthonyvetter** [comment]
Link: https://tanzu.vmware.com/developer/practices/plus-delta-feedback/
