### ISSUE TITLE
Practice: Post Mortem

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#803]
Summary: Exercise to learn from the incident to avoid the same mistake 

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [x] Partially written and/or draft in progress
- [ ] Not yet written

## Maturity of this Practice
- [ ] Very Mature: well established and widely used by our organization and others
- [x] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

Draft content: See internal VMware Confluence page "Practices and Workshops"

Contact with context: Fani Bahar Mihaela Roman

**Comment by fanibahar** [comment]
hi @joemoore we are currently working on it. This is the document: https://docs.google.com/document/d/1JxUACyfq4akD4wmEUa0ID8rDw4xs9VI2mHCjX_hkIns/edit

**Comment by fanibahar** [comment]
Hi @joemoore the final content of the post mortem practices is available here: https://docs.google.com/document/d/1JxUACyfq4akD4wmEUa0ID8rDw4xs9VI2mHCjX_hkIns/edit

We will post it in the slack channel to get feedback. One thing is still wip is the miro template

**Comment by fanibahar** [comment]
hi @joemoore I have resolved all the feedback in the docs. And so far I havent received any more comment or feedback. Do you think we can publish it?

**Comment by joemoore** [comment]
I'll get the preview version published today

**Comment by fanibahar** [comment]
hi @joemoore I wonder where I can check out the preview for this workshop?

**Comment by joemoore** [comment]
@mkollasch-vmware is going to provide some suggested edits if that's okay.
