### ISSUE TITLE
Practcie: About Technical Discovery

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#804]
Summary: This page is to learn about the process of Technical Discovery. It contains information on where to start, an overview of possible goals, advice from other practitioners and links to relevant practices.

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [x] Partially written and/or draft in progress
- [ ] Not yet written

## Maturity of this Practice
- [ ] Very Mature: well established and widely used by our organization and others
- [x] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

Draft content: See internal Google drive folder: https://drive.google.com/drive/folders/1KCXy88z2ChvYEYbKNYMrA85-upd6GjNx

Contact with context: Gagandeep Kaur

## Contribution Guide
Please refer to the [Tanzu Practices Contrition Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Tanzu-Labs-Practices-Contribution-Guide) for detailed instructions.

**Comment by lmalcher-vmw** [comment]
@joemoore I think we can clear this from the backlog now this is published. What do you think? https://tanzu.vmware.com/developer/guides/running-a-technical-discovery/

**Comment by lmalcher-vmw** [comment]
@joemoore  can we consider this done? https://tanzu.vmware.com/developer/guides/guide-to-discovery-and-framing/

**Comment by joemoore** [comment]
Yes, good call. Thank you for doing some backlog maintenance. Closing.
