### ISSUE TITLE
Team Working Agreement - Well Established, Never Published

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#810]
Within the Tanzu Labs Services devision we perform establish Team Working Agreements regularly, often multiple times on within the same team as team structure or staff changes. 

Note: this is a related to or is a duplicate of #811 

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [ ] Partially written and/or draft in progress
- [x] Not yet written

## Maturity of this Practice
- [ ] Very Mature: well established and widely used by our organization and others
- [x] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

## Contribution Guide
Please refer to the [Tanzu Practices Contrition Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Tanzu-Labs-Practices-Contribution-Guide) for detailed instructions.

**Comment by mqsley** [comment]
I am interested in working on this

**Comment by joemoore** [comment]
Great! I've assigned you and will move this into the In Progress column.

**Comment by mqsley** [comment]
DRAFT: https://docs.google.com/document/d/1RJCNDNzXwRmG5cMyOZGvuIDiTFc1zxDwXDLcrGzVRRA/edit?usp=sharing
