### ISSUE TITLE
Large File Storage Solution

### ISSUE THREAD

**Issue by BrianMMcClain** [vmware-tanzu/tanzu-dev-portal#814]
Not an issue currently, but as we start serving more larger static files, we should look into a way to store and serve these outside of storing them in git

There's a conversation to revisit about perhaps about creating an S3 bucket. We can also look into Netlify's CDN capabilities

**Comment by zmb3** [comment]
There's also [Netlify Large Media](https://www.netlify.com/blog/2019/02/26/manage-your-code-and-assets-together-with-netlify-large-media/) which uses Git LFS (the files appear and are versioned in the git repo, but the repo itself actually only contains a pointer to the file on Netlify storage).

**Comment by bryanfriedman** [comment]
We have an S3 bucket for this if we need it.
