### ISSUE TITLE
Practice: Pre Mortem

### ISSUE THREAD

**Issue by fanibahar** [vmware-tanzu/tanzu-dev-portal#821]
Summary: Exercise to identify risk before launch a product and how to avoid it

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [ ] Partially written and/or draft in progress
- [x] Not yet written

## Maturity of this Practice
- [ ] Very Mature: well established and widely used by our organization and others
- [ ] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

## Contribution Guide
Please refer to the [Tanzu Practices Contrition Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Tanzu-Labs-Practices-Contribution-Guide) for detailed instructions.

**Comment by MihaelaRR** [comment]
Link to Draft 
https://docs.google.com/document/d/1CccsycWl-92R6ldoeeR0KsVg9BlLIZyUecFxAUIyi1g/edit

**Comment by joemoore** [comment]
Assigned to @MihaelaRR
