### ISSUE TITLE
Practice: IPMs (Iteration Planning Meetings)

### ISSUE THREAD

**Issue by chliuPivotal** [vmware-tanzu/tanzu-dev-portal#825]
## Summary
Iteration Planning Meetings (IPMs) are core to our agile development practice and serve as a regular (ideally weekly) opportunity for a development team to get in sync about the vision and effort for the work intended for the next iteration.

This is a well-established practice amongst Labs practitioners, that has not ever been fully published/documented as a practice.

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [ ] Partially written and/or draft in progress
- [x] Not yet written

## Maturity of this Practice
- [x] Very Mature: well established and widely used by our organization and others
- [ ] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

## Resources 
- Links to articles and blog posts (TBD if any prove valuable)
- Links to presentations, videos, books, etc.

**Note:** If these resources are not public (i.e. an internal document), provide _publicly safe information_ about how someone with the proper access would find these resources. **Do not post insecure links or non-public information here**.

**Comment by darryl-snow** [comment]
🙋🏻‍♂️ I'm interested in working on this

**Comment by darryl-snow** [comment]
https://docs.google.com/document/d/1X_NZzTP7dUVO9ycRXAQ37DUPWXwstjDQqkZGqCpZCbA/edit
