### ISSUE TITLE
Practice: Stack Ranking

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#845]
## Summary
Stack ranking is a technique which involves taking a list of options (ideas, problems, stories, etc.) and ordering them along an axis according to a single criterion (e.g. value, importance, cost, complexity, risk, etc.)

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [x] Partially written and/or draft in progress
- [ ] Not yet written

## Maturity of this Practice
- [ ] Very Mature: well established and widely used by our organization and others
- [x] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

## Resources 
- Conversation in #tanzu-practice-site
- See internal VMware working doc. 

**Note:** If these resources are not public (i.e. an internal document), provide _publicly safe information_ about how someone with the proper access would find these resources. **Do not post insecure links or non-public information here**.

**Comment by joemoore** [comment]
In progress by @lucaishovmware

**Comment by joemoore** [comment]
Note this was started but stalled out. Moving back to ToDo for now.

**Comment by chliuPivotal** [comment]
@joemoore - any takers on this one? I'd be happy to pick it up from where it left off.

**Comment by joemoore** [comment]
@chliuPivotal You might check with @lucaishovmware who originally had this idea. I'll hit you both up on Slack.

**Comment by joemoore** [comment]
Assigned!

**Comment by joemoore** [comment]
@chliuPivotal @lucaishovmware Is there a doc we can add here for reference?
