### ISSUE TITLE
Publish the app-development Double Diamond as a reference for practices at certain stages

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#846]
## Summary
The VMware internal site has valuable Process page that associates practices/workshops with different phases of the application discovery, framing, and delivery process. We need a version of that page that delivers similar or better value. 

![Screen Shot 2021-05-13 at 9 21 33 AM](https://user-images.githubusercontent.com/13995/118165777-ee2ef380-b3e1-11eb-8eeb-1d3c89f9d44c.png)

## Contribution Guide
Please refer to the [Tanzu Practices Contrition Guide](https://github.com/vmware-tanzu/tanzu-dev-portal/wiki/Tanzu-Labs-Practices-Contribution-Guide) for detailed instructions.

**Comment by joemoore** [comment]
Great conversation and resources here: https://vmware.slack.com/archives/CUF2HLB5W/p1638222418134700

**Comment by joemoore** [comment]
We might consider converting this to a [Guide](https://tanzu.vmware.com/developer/guides/), though the fancy linking would not be possible.

**Comment by lmalcher-vmw** [comment]
@joemoore Can we consider this done? https://tanzu.vmware.com/developer/guides/guide-to-discovery-and-framing/

**Comment by joemoore** [comment]
Good call! Closing.
