### ISSUE TITLE
Add and Expose Outcomes Metadata

### ISSUE THREAD

**Issue by BrianMMcClain** [vmware-tanzu/tanzu-dev-portal#851]
The initial design of outcomes include the following metadata:

1. The audience the outcome is intended for (Beginner, Intermediate, Advanced)
2. Estimated time to work through the entire outcome

If possible, it would be great to add this metadata to each outcome. A design mockup exists for this as well so we can coordinate with the design team to implement it. In the mean time I'll try to track it down to add a screenshot.

**Comment by bryanfriedman** [comment]
We don't have outcomes anymore...
