### ISSUE TITLE
broken_link test failing when updating remote branch from main in GitHub UI

### ISSUE THREAD

**Issue by anthonyvetter** [vmware-tanzu/tanzu-dev-portal#954]
**Describe the bug**
In a PR, if the branch is out of date with main, and in the UI you use the button for updating the branch, the GH Actions tests will rerun. 3 out of the last 3 times I did this, the broken_links test failed. Rerunning the test will allow it to pass. Here is an example of one of the failures: https://github.com/vmware-tanzu/tanzu-dev-portal/pull/932/checks?check_run_id=2806325383

**To Reproduce**
1. Open a PR with a remote branch
2. Wait for the branch to get out of date with Main (see the button to reconcile in the PR)
3. Click the button to update the branch
4. See error when the test fails

**Expected behavior**
I would expect the test to pass, or if failed, fail in a way that doesn't error on seemingly every content piece in TDC

**Screenshots**
https://github.com/vmware-tanzu/tanzu-dev-portal/pull/932/checks?check_run_id=2806325383

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Safari 14.1.1

**Comment by BrianMMcClain** [comment]
For a bit more info, this seems to be happening more and more any time the link_check check is ran, not just when rebasing a branch from main. 

I've marked this with the "priority" tag since this issue is happening more frequently and is becoming a long delay in the development cycle

**Comment by BrianMMcClain** [comment]
Updated broken link test as a part of #1876 which should help resolve this
