### ISSUE TITLE
Is there a way to hide the "featured" taxonomy?

### ISSUE THREAD

**Issue by bryanfriedman** [vmware-tanzu/tanzu-dev-portal#96]
It's not a huge deal but this page is weird: http://localhost:1313/featured/

**Comment by BrianMMcClain** [comment]
@bryanfriedman with a cursory look around, it looks like the best we could do is a post-build step to remove the `public/developer/featured` directory. Only configuration options I can find are an all-or-nothing enable/disable all taxonomy pages, though perhaps I overlooked something.

**Comment by bryanfriedman** [comment]
Featured taxonomy not even used anymore.
