### ISSUE TITLE
Practice: Pre-IPM

### ISSUE THREAD

**Issue by joemoore** [vmware-tanzu/tanzu-dev-portal#965]
## Summary
Session prior to the team Iteration Planning Meeting, this session brings at least one member from the Balanced Team together to discuss, vet, size, shape, and sometimes write User Stories to be presented during IPM. This help the IPM run more smoothly, helps pre-answer common questions, and conveys context to at least one member each from the balanced team who can help explain the stories to the rest of the group.

## Progress and Publication Status
- [ ] Already published on the Tanzu Developer Center.
- [ ] Published internally or elsewhere; needs review for Tanzu Developer Center publication
- [ ] Partially written and/or draft in progress
- [x] Not yet written

## Maturity of this Practice
- [x] Very Mature: well established and widely used by our organization and others
- [ ] Mature: have successfully used many times with many teams / projects
- [ ] Immature: have used several or many times but is evolving quite a bit with each usage
- [ ] Incubating: have used a few times, still rapidly evolving, has promise but unsure if generally applicable across many teams

## Resources 
- Links to articles and blog posts
- Links to presentations, videos, books, etc.

**Note:** If these resources are not public (i.e. an internal document), provide _publicly safe information_ about how someone with the proper access would find these resources. **Do not post insecure links or non-public information here**.

**Comment by mkollasch-vmware** [comment]
I've got a few days to spare, during which I'm interested in working on this. I'll ensure it's a good complement to the IPM practice and ensure they link to each other.

**Comment by joemoore** [comment]
Please let us know how we can help!
