### ISSUE TITLE
Videos Issue: Simplify Building Containers w/ Cloud Native Buildpacks

### ISSUE THREAD

**Issue by dcorricelli** [vmware-tanzu/tanzu-dev-portal#981]
**Describe the bug**
The video appears to have been removed by the Youtube owner

**To Reproduce**
1. Go to the page: https://tanzu.vmware.com/developer/videos/cloudnativebuildpacks-lightboard/
2. Click on 'play'
4. See error 'video unavailalable - the video has been removed by the uploader'

**Expected behavior**
The video plays

**Screenshots**

![Screen Shot 2021-06-21 at 9 11 46 AM](https://user-images.githubusercontent.com/44910714/122767480-b7fe5280-d270-11eb-84f6-436f4c827ed4.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 91

**Comment by BrianMMcClain** [comment]
Appreciate the report! I just posed up a fix for this so should be updated on the live site in just a few minutes. Thanks!
